### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by jeking3** [boostorg/contract#13]
Consider adding https://github.com/jeking3/boost-ci to improve quality.

**Comment by lcaminiti** [comment]
I am not familiar with Boost.CI (is it an officially release component of Boost, like BJam?). I'll look into it can consider it if/when a new release of Boost.Contract is required.

**Comment by jeking3** [comment]
Not officially, but I am part of the Community Maintenance Team and have been using it over the last year on about 20 boost repositories to improve quality.

**Comment by jeking3** [comment]
If you copy the LICENSE file out of Boost.Assign into the top level of your repo, GitHub will automatically tag it using BSL-1.0 for licensing.

**Comment by jeking3** [comment]
The AppVeyor build results should be ready around 12AM EST.
Travis is building now.  I opened some issues related to the failures I've seen so far.

AppVeyor Build Results: https://ci.appveyor.com/project/jeking3/contract/builds/20042520
Travis CI Build Results: https://travis-ci.org/jeking3/contract/builds/450610128

**Comment by lcaminiti** [comment]
OK, I will consider adding Boost.CI to Boost.Contract.

**Comment by lcaminiti** [comment]
I won't have time to add Boost.CI to Boost.Contract in release 1.1.0. However, this would be a good thing to do since it already found a couple of errors when it was ran locally by jeking3... it could also be done by whomever has the time to do so. Maybe do it and send me a pull request for consideration.

**Comment by jeking3** [comment]
I'm working on this:

https://github.com/jeking3/contract/pull/1

However the test suite for Boost.Contract seems to take a long time and is causing timeouts.  I have to pare down the language levels supported in the build jobs I guess.  Why do the tests take such a long time?  I haven't looked yet.

**Comment by lcaminiti** [comment]
Make sure you only run the tests under the test/ directory (you don't need to run the examples under the example/ directory instead). I think the tests take a long time just because there's really a lot of them, one for every feature and there's quite a few combinations to test (there's ever more combinations if you consider contracts that can selectively disable at compile-time #defining the BOOST_CONTRACT_NO_... macros but these extra test permutations which really take days to run are not part of the default test build unless you specify extra bjam params bc_no=...).
