### ISSUE TITLE
invalid website address

### ISSUE THREAD

**Issue by morris-stock** [boostorg/contract#8]
http://www.boost.org/doc/libs/1_66_0/libs/contract/doc/html/index.html returns 404 Not Found.

find valid here at http://www.boost.org/doc/libs/develop/libs/contract/doc/html/index.html

**Comment by lcaminiti** [comment]
I changed this link as suggested. It should work now.

NOTE: I originally did this on purpose because I wanted to point to the official release doc. But there's no release yet, plus on github you get the develop branch by default so it might better to the doc link in github to also point to the ones built from develop.
