### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by gizmo1904** [boostorg/contract#9]
I was wondering if it's possible to use the library without exception support. I couldn't find any information on that and I can't compile with -fno-exceptions. Is it not possible?

**Comment by lcaminiti** [comment]
This won't work now. I will look if it is possible to add this for the next Boost release, but probably it won't be possible because the library uses exceptions internally to signal a contract assertion failure.

In fact, any exception thrown from within functions/functors used to check preconditions, postconditions, etc. is handled by the library as a contract assertion failure. BOOST_CONTRACT_ASSERT does nothing more than throwing an exception with __FILE__ and __LINE__ info when its contract condition fails. Because of that, I don't think I can make the lib implementation work without exception support... but I'll look into it.

Either way, I will document this.

**Comment by gizmo1904** [comment]
Okay, thanks for the clarification.

**Comment by lcaminiti** [comment]
This won't work because the library uses exceptions internally to signal contract failures.
